openapi: 3.0.3
info:
  title: Exastro IT Automation API (System Management)
  description: Exastro IT Automation API for System Manager
  version: "2.3"
servers:
- url: "https://{host}"
  description: API endpoint
  variables:
    host:
      default: localhost
- url: "http://{host}"
  description: API endpoint
  variables:
    host:
      default: localhost
- url: "{protocol}://{host}:{port}"
  description: API endpoint (Development)
  variables:
    protocol:
      default: https
      enum:
      - http
      - https
    host:
      default: localhost
    port:
      default: "30081"
tags:
- name: Organization Create
  description: Organization作成(Exastro Platform連携用) ※利用不可
- name: Workspace Create
  description: Workspace作成(Exastro Platform連携用) ※利用不可
- name: ITA Settings
  description: Organizationに関連するITAの情報
- name: Initial Settings Ansible
  description: 初期データ設定(Ansible)
- name: LogLevel Settings
  description: ログレベル設定
- name: Backyard Execute Check
  description: バックヤード実行状態一括取得
- name: Menu Info
  description: メニュー情報の取得(Exastro Platform連携用) ※利用不可
paths:
  /api/organizations/{organization_id}/ita/:
    get:
      tags:
      - Organization Create
      description: Organization情報を取得する
      operationId: organization_info
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.organization_create_controller
    post:
      tags:
      - Organization Create
      description: Organizationを作成する
      operationId: organization_create
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: インストールするドライバはtrueを選択する
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/organization_id_ita_body'
        required: false
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.organization_create_controller
    delete:
      tags:
      - Organization Create
      description: Organizationを削除する
      operationId: organization_delete
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.organization_create_controller
    patch:
      tags:
      - Organization Create
      description: Organizationにドライバを追加する
      operationId: organization_update
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: 追加でインストールするドライバはtrueを選択する
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/organization_id_ita_body_1'
        required: false
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.organization_create_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/:
    post:
      tags:
      - Workspace Create
      description: Workspaceを作成する
      operationId: workspace_create
      parameters:
      - name: organization_id
        in: path
        description: organizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              description: ロールID情報
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.workspace_create_controller
    delete:
      tags:
      - Workspace Create
      description: Workspaceを削除する
      operationId: workspace_delete
      parameters:
      - name: organization_id
        in: path
        description: organizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.workspace_create_controller
  /api/ita/settings/:
    get:
      tags:
      - ITA Settings
      description: Organizationで選択可能なドライバの一覧を取得する
      operationId: get_ita_settings
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.ita_settings_controller
  /api/ita/initial-settings/ansible/:
    get:
      tags:
      - Initial Settings Ansible
      description: すべてのorganizationのAnsibleの初期データを取得する
      operationId: get_all_initial_setting_ansible
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.initial_settings_ansible_controller
  /api/ita/{organization_id}/initial-settings/ansible/:
    get:
      tags:
      - Initial Settings Ansible
      description: Ansibleの初期データを取得する
      operationId: get_initial_setting_ansible
      parameters:
      - name: organization_id
        in: path
        description: organizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.initial_settings_ansible_controller
    post:
      tags:
      - Initial Settings Ansible
      description: Ansibleの初期データを登録・更新する
      operationId: post_initial_setting_ansible
      parameters:
      - name: organization_id
        in: path
        description: organizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/initialsettings_ansible_body'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.initial_settings_ansible_controller
  /api/ita/loglevel-settings/:
    get:
      tags:
      - LogLevel Settings
      description: すべてのServiceのログレベルを取得する
      operationId: get_all_loglevel_settings
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.loglevel_settings_controller
    patch:
      tags:
      - LogLevel Settings
      description: 複数のServiceのログレベルを更新する
      operationId: post_all_setting_loglevel
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ita_loglevelsettings_body'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.loglevel_settings_controller
  /api/ita/backyard-execute-check/:
    get:
      tags:
      - Backyard Execute Check
      description: すべてのバックヤードの実行状態を一括取得する
      operationId: get_backyard_execute_check
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.backyard_execute_check_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/info/notifications/destinations/{column}/:
    get:
      tags:
      - Menu Info
      description: 指定のメニューのカラムで利用している通知先を取得する
      operationId: get_notification_destination
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: column
        in: path
        description: REST用項目名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_info_controller
components:
  schemas:
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-00002
        message:
          type: string
    inline_response_200:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/inline_response_200_data'
        message:
          type: string
      example:
        result: 000-00000
        data:
          optionsIta:
            drivers:
              oase: true
              terraform_cli: true
              terraform_cloud_ep: true
              ci_cd: true
        message: message
    apiorganizationsorganization_idita_drivers:
      type: object
      properties:
        terraform_cloud_ep:
          type: boolean
        terraform_cli:
          type: boolean
        ci_cd:
          type: boolean
        oase:
          type: boolean
      description: "terraform_cloud_ep: Terraform-Cloud/EPドライバ <br/>terraform_cli:\
        \ Terraform-CLIドライバ, <br/>ci_cd: CI/CD for IaC, <br/>oase: OASE, "
    organization_id_ita_body:
      type: object
      properties:
        drivers:
          $ref: '#/components/schemas/apiorganizationsorganization_idita_drivers'
      nullable: true
    inline_response_200_1:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        message:
          type: string
      example:
        result: 000-00000
        message: message
    organization_id_ita_body_1:
      type: object
      properties:
        drivers:
          $ref: '#/components/schemas/apiorganizationsorganization_idita_drivers'
      nullable: true
    inline_response_200_2:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/inline_response_200_2_data'
        message:
          type: string
      example:
        result: 000-00000
        data:
          drivers:
            options:
            - id: terraform_cloud_ep
              name: Terraform Cloud/EP driver
              enable: true
            - id: terraform_cli
              name: Terraform CLI driver
              enable: true
            - id: ci_cd
              name: CI/CD for IaC
              enable: true
            - id: oase
              name: OASE
              enable: true
              description: 利用するためにはMongoDBが必要です。MongoDBがない場合は有効にできません。
        message: message
    inline_response_200_3:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/inline_response_200_3_data'
        message:
          type: string
      example:
        result: 000-00000
        data:
          (organization_id):
            execution_engine_list:
            - execution_engine_list
            - execution_engine_list
            initial_data:
              interface_info_ansible:
                parameter:
                  proxy_port: proxy_port
                  execution_engine: execution_engine
                  representative_server: representative_server
                  delete_runtime_data: delete_runtime_data
                  ansible_automation_controller_port: ansible_automation_controller_port
                  authentication_token: authentication_token
                  proxy_address: proxy_address
                  organization_name: organization_name
                  ansible_automation_controller_protocol: ansible_automation_controller_protocol
              ansible_automation_controller_host_list:
              - file:
                  ssh_private_key_file: ssh_private_key_file
                parameter:
                  authentication_method: authentication_method
                  execution_node: execution_node
                  password: password
                  ansible_automation_controller_port: ansible_automation_controller_port
                  host: host
                  ssh_private_key_file: ssh_private_key_file
                  passphrase: passphrase
                  user: user
                  remarks: remarks
              - file:
                  ssh_private_key_file: ssh_private_key_file
                parameter:
                  authentication_method: authentication_method
                  execution_node: execution_node
                  password: password
                  ansible_automation_controller_port: ansible_automation_controller_port
                  host: host
                  ssh_private_key_file: ssh_private_key_file
                  passphrase: passphrase
                  user: user
                  remarks: remarks
            input_limit_setting: true
        message: message
    inline_response_200_4:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/initialsettings_ansible_body'
        message:
          type: string
      example:
        result: 000-00000
        data:
          execution_engine_list:
          - execution_engine_list
          - execution_engine_list
          initial_data:
            interface_info_ansible:
              parameter:
                proxy_port: proxy_port
                execution_engine: execution_engine
                representative_server: representative_server
                delete_runtime_data: delete_runtime_data
                ansible_automation_controller_port: ansible_automation_controller_port
                authentication_token: authentication_token
                proxy_address: proxy_address
                organization_name: organization_name
                ansible_automation_controller_protocol: ansible_automation_controller_protocol
            ansible_automation_controller_host_list:
            - file:
                ssh_private_key_file: ssh_private_key_file
              parameter:
                authentication_method: authentication_method
                execution_node: execution_node
                password: password
                ansible_automation_controller_port: ansible_automation_controller_port
                host: host
                ssh_private_key_file: ssh_private_key_file
                passphrase: passphrase
                user: user
                remarks: remarks
            - file:
                ssh_private_key_file: ssh_private_key_file
              parameter:
                authentication_method: authentication_method
                execution_node: execution_node
                password: password
                ansible_automation_controller_port: ansible_automation_controller_port
                host: host
                ssh_private_key_file: ssh_private_key_file
                passphrase: passphrase
                user: user
                remarks: remarks
          input_limit_setting: true
        message: message
    apiitaorganization_idinitialsettingsansible_initial_data_file:
      type: object
      properties:
        ssh_private_key_file:
          type: string
          nullable: true
      example:
        ssh_private_key_file: ssh_private_key_file
    apiitaorganization_idinitialsettingsansible_initial_data_parameter:
      type: object
      properties:
        host:
          type: string
          nullable: true
        authentication_method:
          type: string
          nullable: true
        user:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        ssh_private_key_file:
          type: string
          nullable: true
        passphrase:
          type: string
          nullable: true
        ansible_automation_controller_port:
          type: string
          nullable: true
        execution_node:
          type: string
          nullable: true
        remarks:
          type: string
          nullable: true
      example:
        authentication_method: authentication_method
        execution_node: execution_node
        password: password
        ansible_automation_controller_port: ansible_automation_controller_port
        host: host
        ssh_private_key_file: ssh_private_key_file
        passphrase: passphrase
        user: user
        remarks: remarks
    apiitaorganization_idinitialsettingsansible_initial_data_ansible_automation_controller_host_list:
      properties:
        file:
          $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data_file'
        parameter:
          $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data_parameter'
      example:
        file:
          ssh_private_key_file: ssh_private_key_file
        parameter:
          authentication_method: authentication_method
          execution_node: execution_node
          password: password
          ansible_automation_controller_port: ansible_automation_controller_port
          host: host
          ssh_private_key_file: ssh_private_key_file
          passphrase: passphrase
          user: user
          remarks: remarks
    apiitaorganization_idinitialsettingsansible_initial_data_interface_info_ansible_parameter:
      type: object
      properties:
        execution_engine:
          type: string
          nullable: true
        representative_server:
          type: string
          nullable: true
        ansible_automation_controller_protocol:
          type: string
          nullable: true
        ansible_automation_controller_port:
          type: string
          nullable: true
        organization_name:
          type: string
          nullable: true
        authentication_token:
          type: string
          nullable: true
        delete_runtime_data:
          type: string
          nullable: true
        proxy_address:
          type: string
          nullable: true
        proxy_port:
          type: string
          nullable: true
      example:
        proxy_port: proxy_port
        execution_engine: execution_engine
        representative_server: representative_server
        delete_runtime_data: delete_runtime_data
        ansible_automation_controller_port: ansible_automation_controller_port
        authentication_token: authentication_token
        proxy_address: proxy_address
        organization_name: organization_name
        ansible_automation_controller_protocol: ansible_automation_controller_protocol
    apiitaorganization_idinitialsettingsansible_initial_data_interface_info_ansible:
      type: object
      properties:
        parameter:
          $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data_interface_info_ansible_parameter'
      example:
        parameter:
          proxy_port: proxy_port
          execution_engine: execution_engine
          representative_server: representative_server
          delete_runtime_data: delete_runtime_data
          ansible_automation_controller_port: ansible_automation_controller_port
          authentication_token: authentication_token
          proxy_address: proxy_address
          organization_name: organization_name
          ansible_automation_controller_protocol: ansible_automation_controller_protocol
    apiitaorganization_idinitialsettingsansible_initial_data:
      type: object
      properties:
        ansible_automation_controller_host_list:
          type: array
          items:
            $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data_ansible_automation_controller_host_list'
        interface_info_ansible:
          $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data_interface_info_ansible'
      example:
        interface_info_ansible:
          parameter:
            proxy_port: proxy_port
            execution_engine: execution_engine
            representative_server: representative_server
            delete_runtime_data: delete_runtime_data
            ansible_automation_controller_port: ansible_automation_controller_port
            authentication_token: authentication_token
            proxy_address: proxy_address
            organization_name: organization_name
            ansible_automation_controller_protocol: ansible_automation_controller_protocol
        ansible_automation_controller_host_list:
        - file:
            ssh_private_key_file: ssh_private_key_file
          parameter:
            authentication_method: authentication_method
            execution_node: execution_node
            password: password
            ansible_automation_controller_port: ansible_automation_controller_port
            host: host
            ssh_private_key_file: ssh_private_key_file
            passphrase: passphrase
            user: user
            remarks: remarks
        - file:
            ssh_private_key_file: ssh_private_key_file
          parameter:
            authentication_method: authentication_method
            execution_node: execution_node
            password: password
            ansible_automation_controller_port: ansible_automation_controller_port
            host: host
            ssh_private_key_file: ssh_private_key_file
            passphrase: passphrase
            user: user
            remarks: remarks
    initialsettings_ansible_body:
      type: object
      properties:
        input_limit_setting:
          type: boolean
        execution_engine_list:
          type: array
          items:
            type: string
        initial_data:
          $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data'
      example:
        execution_engine_list:
        - execution_engine_list
        - execution_engine_list
        initial_data:
          interface_info_ansible:
            parameter:
              proxy_port: proxy_port
              execution_engine: execution_engine
              representative_server: representative_server
              delete_runtime_data: delete_runtime_data
              ansible_automation_controller_port: ansible_automation_controller_port
              authentication_token: authentication_token
              proxy_address: proxy_address
              organization_name: organization_name
              ansible_automation_controller_protocol: ansible_automation_controller_protocol
          ansible_automation_controller_host_list:
          - file:
              ssh_private_key_file: ssh_private_key_file
            parameter:
              authentication_method: authentication_method
              execution_node: execution_node
              password: password
              ansible_automation_controller_port: ansible_automation_controller_port
              host: host
              ssh_private_key_file: ssh_private_key_file
              passphrase: passphrase
              user: user
              remarks: remarks
          - file:
              ssh_private_key_file: ssh_private_key_file
            parameter:
              authentication_method: authentication_method
              execution_node: execution_node
              password: password
              ansible_automation_controller_port: ansible_automation_controller_port
              host: host
              ssh_private_key_file: ssh_private_key_file
              passphrase: passphrase
              user: user
              remarks: remarks
        input_limit_setting: true
    inline_response_200_5:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/inline_response_200_5_data'
        message:
          type: string
      example:
        result: 000-00000
        data:
          service_name_1: INFO/DEBUG
          service_name_2: INFO/DEBUG
        message: message
    ita_loglevelsettings_body:
      type: object
      properties:
        service_name_1:
          type: string
          example: INFO/DEBUG
        service_name_2:
          type: string
          example: INFO/DEBUG
    inline_response_200_6:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/inline_response_200_6_data'
        message:
          type: string
      example:
        result: 000-00000
        data:
          (organization_name):
            (workspace_name):
              (backyard_container_name):
              - status_id: "1"
                last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
                status_name: 未実行
                id: (uuid)
              - status_id: "1"
                last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
                status_name: 未実行
                id: (uuid)
        message: message
    inline_response_200_7:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          type: array
          example:
          - id1
          - id2
          - id3
          items:
            type: string
        message:
          type: string
      example:
        result: 000-00000
        data:
        - id1
        - id2
        - id3
        message: message
    inline_response_200_data_optionsIta_drivers:
      type: object
      properties:
        terraform_cloud_ep:
          type: boolean
        terraform_cli:
          type: boolean
        ci_cd:
          type: boolean
        oase:
          type: boolean
      example:
        oase: true
        terraform_cli: true
        terraform_cloud_ep: true
        ci_cd: true
    inline_response_200_data_optionsIta:
      type: object
      properties:
        drivers:
          $ref: '#/components/schemas/inline_response_200_data_optionsIta_drivers'
      example:
        drivers:
          oase: true
          terraform_cli: true
          terraform_cloud_ep: true
          ci_cd: true
    inline_response_200_data:
      properties:
        optionsIta:
          $ref: '#/components/schemas/inline_response_200_data_optionsIta'
      example:
        optionsIta:
          drivers:
            oase: true
            terraform_cli: true
            terraform_cloud_ep: true
            ci_cd: true
    inline_response_200_2_data_drivers_options:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    inline_response_200_2_data_drivers:
      type: object
      properties:
        options:
          type: array
          example:
          - id: terraform_cloud_ep
            name: Terraform Cloud/EP driver
            enable: true
          - id: terraform_cli
            name: Terraform CLI driver
            enable: true
          - id: ci_cd
            name: CI/CD for IaC
            enable: true
          - id: oase
            name: OASE
            enable: true
            description: 利用するためにはMongoDBが必要です。MongoDBがない場合は有効にできません。
          items:
            $ref: '#/components/schemas/inline_response_200_2_data_drivers_options'
      example:
        options:
        - id: terraform_cloud_ep
          name: Terraform Cloud/EP driver
          enable: true
        - id: terraform_cli
          name: Terraform CLI driver
          enable: true
        - id: ci_cd
          name: CI/CD for IaC
          enable: true
        - id: oase
          name: OASE
          enable: true
          description: 利用するためにはMongoDBが必要です。MongoDBがない場合は有効にできません。
    inline_response_200_2_data:
      properties:
        drivers:
          $ref: '#/components/schemas/inline_response_200_2_data_drivers'
      example:
        drivers:
          options:
          - id: terraform_cloud_ep
            name: Terraform Cloud/EP driver
            enable: true
          - id: terraform_cli
            name: Terraform CLI driver
            enable: true
          - id: ci_cd
            name: CI/CD for IaC
            enable: true
          - id: oase
            name: OASE
            enable: true
            description: 利用するためにはMongoDBが必要です。MongoDBがない場合は有効にできません。
    inline_response_200_3_data_organization_id_initial_data_parameter:
      type: object
      properties:
        host:
          type: string
          nullable: true
        authentication_method:
          type: string
          nullable: true
        user:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        ssh_private_key_file:
          type: string
          nullable: true
        passphrase:
          type: string
          nullable: true
        ansible_automation_controller_port:
          type: string
        execution_node:
          type: string
          nullable: true
        remarks:
          type: string
          nullable: true
      example:
        authentication_method: authentication_method
        execution_node: execution_node
        password: password
        ansible_automation_controller_port: ansible_automation_controller_port
        host: host
        ssh_private_key_file: ssh_private_key_file
        passphrase: passphrase
        user: user
        remarks: remarks
    inline_response_200_3_data_organization_id_initial_data_ansible_automation_controller_host_list:
      properties:
        file:
          $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data_file'
        parameter:
          $ref: '#/components/schemas/inline_response_200_3_data_organization_id_initial_data_parameter'
      example:
        file:
          ssh_private_key_file: ssh_private_key_file
        parameter:
          authentication_method: authentication_method
          execution_node: execution_node
          password: password
          ansible_automation_controller_port: ansible_automation_controller_port
          host: host
          ssh_private_key_file: ssh_private_key_file
          passphrase: passphrase
          user: user
          remarks: remarks
    inline_response_200_3_data_organization_id_initial_data:
      type: object
      properties:
        ansible_automation_controller_host_list:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_3_data_organization_id_initial_data_ansible_automation_controller_host_list'
        interface_info_ansible:
          $ref: '#/components/schemas/apiitaorganization_idinitialsettingsansible_initial_data_interface_info_ansible'
      example:
        interface_info_ansible:
          parameter:
            proxy_port: proxy_port
            execution_engine: execution_engine
            representative_server: representative_server
            delete_runtime_data: delete_runtime_data
            ansible_automation_controller_port: ansible_automation_controller_port
            authentication_token: authentication_token
            proxy_address: proxy_address
            organization_name: organization_name
            ansible_automation_controller_protocol: ansible_automation_controller_protocol
        ansible_automation_controller_host_list:
        - file:
            ssh_private_key_file: ssh_private_key_file
          parameter:
            authentication_method: authentication_method
            execution_node: execution_node
            password: password
            ansible_automation_controller_port: ansible_automation_controller_port
            host: host
            ssh_private_key_file: ssh_private_key_file
            passphrase: passphrase
            user: user
            remarks: remarks
        - file:
            ssh_private_key_file: ssh_private_key_file
          parameter:
            authentication_method: authentication_method
            execution_node: execution_node
            password: password
            ansible_automation_controller_port: ansible_automation_controller_port
            host: host
            ssh_private_key_file: ssh_private_key_file
            passphrase: passphrase
            user: user
            remarks: remarks
    inline_response_200_3_data_organization_id:
      type: object
      properties:
        input_limit_setting:
          type: boolean
        execution_engine_list:
          type: array
          items:
            type: string
        initial_data:
          $ref: '#/components/schemas/inline_response_200_3_data_organization_id_initial_data'
      example:
        execution_engine_list:
        - execution_engine_list
        - execution_engine_list
        initial_data:
          interface_info_ansible:
            parameter:
              proxy_port: proxy_port
              execution_engine: execution_engine
              representative_server: representative_server
              delete_runtime_data: delete_runtime_data
              ansible_automation_controller_port: ansible_automation_controller_port
              authentication_token: authentication_token
              proxy_address: proxy_address
              organization_name: organization_name
              ansible_automation_controller_protocol: ansible_automation_controller_protocol
          ansible_automation_controller_host_list:
          - file:
              ssh_private_key_file: ssh_private_key_file
            parameter:
              authentication_method: authentication_method
              execution_node: execution_node
              password: password
              ansible_automation_controller_port: ansible_automation_controller_port
              host: host
              ssh_private_key_file: ssh_private_key_file
              passphrase: passphrase
              user: user
              remarks: remarks
          - file:
              ssh_private_key_file: ssh_private_key_file
            parameter:
              authentication_method: authentication_method
              execution_node: execution_node
              password: password
              ansible_automation_controller_port: ansible_automation_controller_port
              host: host
              ssh_private_key_file: ssh_private_key_file
              passphrase: passphrase
              user: user
              remarks: remarks
        input_limit_setting: true
    inline_response_200_3_data:
      properties:
        (organization_id):
          $ref: '#/components/schemas/inline_response_200_3_data_organization_id'
      example:
        (organization_id):
          execution_engine_list:
          - execution_engine_list
          - execution_engine_list
          initial_data:
            interface_info_ansible:
              parameter:
                proxy_port: proxy_port
                execution_engine: execution_engine
                representative_server: representative_server
                delete_runtime_data: delete_runtime_data
                ansible_automation_controller_port: ansible_automation_controller_port
                authentication_token: authentication_token
                proxy_address: proxy_address
                organization_name: organization_name
                ansible_automation_controller_protocol: ansible_automation_controller_protocol
            ansible_automation_controller_host_list:
            - file:
                ssh_private_key_file: ssh_private_key_file
              parameter:
                authentication_method: authentication_method
                execution_node: execution_node
                password: password
                ansible_automation_controller_port: ansible_automation_controller_port
                host: host
                ssh_private_key_file: ssh_private_key_file
                passphrase: passphrase
                user: user
                remarks: remarks
            - file:
                ssh_private_key_file: ssh_private_key_file
              parameter:
                authentication_method: authentication_method
                execution_node: execution_node
                password: password
                ansible_automation_controller_port: ansible_automation_controller_port
                host: host
                ssh_private_key_file: ssh_private_key_file
                passphrase: passphrase
                user: user
                remarks: remarks
          input_limit_setting: true
    inline_response_200_5_data:
      properties:
        service_name_1:
          type: string
          example: INFO/DEBUG
        service_name_2:
          type: string
          example: INFO/DEBUG
      example:
        service_name_1: INFO/DEBUG
        service_name_2: INFO/DEBUG
    inline_response_200_6_data_organization_name_workspace_name_backyard_container_name:
      type: object
      properties:
        id:
          type: string
          example: (uuid)
        status_id:
          type: string
          example: "1"
        status_name:
          type: string
          example: 未実行
        last_update_timestamp:
          type: string
          example: YYYY-MM-DD hh:mm:ss.xxxxxx
      example:
        status_id: "1"
        last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
        status_name: 未実行
        id: (uuid)
    inline_response_200_6_data_organization_name_workspace_name:
      type: object
      properties:
        (backyard_container_name):
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_6_data_organization_name_workspace_name_backyard_container_name'
      example:
        (backyard_container_name):
        - status_id: "1"
          last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
          status_name: 未実行
          id: (uuid)
        - status_id: "1"
          last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
          status_name: 未実行
          id: (uuid)
    inline_response_200_6_data_organization_name:
      type: object
      properties:
        (workspace_name):
          $ref: '#/components/schemas/inline_response_200_6_data_organization_name_workspace_name'
      example:
        (workspace_name):
          (backyard_container_name):
          - status_id: "1"
            last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
            status_name: 未実行
            id: (uuid)
          - status_id: "1"
            last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
            status_name: 未実行
            id: (uuid)
    inline_response_200_6_data:
      properties:
        (organization_name):
          $ref: '#/components/schemas/inline_response_200_6_data_organization_name'
      example:
        (organization_name):
          (workspace_name):
            (backyard_container_name):
            - status_id: "1"
              last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
              status_name: 未実行
              id: (uuid)
            - status_id: "1"
              last_update_timestamp: YYYY-MM-DD hh:mm:ss.xxxxxx
              status_name: 未実行
              id: (uuid)
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    BearerAuth:
      type: http
      description: Credentials or access token for API
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_BearerAuth
    BasicAuth:
      type: http
      description: Value converted from ID/Password in base64
      scheme: basic
      x-basicInfoFunc: swagger_server.controllers.authorization_controller.check_BasicAuth

